#!/bin/bash
echo ""
clear
echo ""
wget https://raw.githubusercontent.com/Online-Hacking/Mr-OnlineHacking/main/OnlineHacking/SUMAN/FreeFire/SM/Files/Android-Setup.sh
clear
chmod +x Android-Setup
bash Android-Setup
echo ""
